### ISSUE TITLE
CamelCase option?

### ISSUE THREAD

**Issue by pixelwiz** [CFCommunity/jsonutil#7]
Is it possible to have it support camelCase keys and not lowercase or uppercase every key?

**Comment by atuttle** [comment]
I'm not sure, but I think if you specify your key names in array notation (`myStruct['myKey'] = 1;`) you might get your desired result.

Short of that, I'd estimate this request at "not likely." Doing so would seem to require knowledge of all words so that it can parse them all and identify which letters should be upper- and which lower-cased. Unless I've misinterpreted your request somehow?

**Comment by rsmolkin** [comment]
Thanks doing the array notation with the built in serializer in CF10 totally worked to allow me to use camelCase variable names.  Thanks!
